version: "3.8"
volumes:
  mysql-db-data:
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - mysql-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cat_app
      # MYSQL_PASSWORD: 123456
    ports:
      - 33060:3306
  cat_app:
    build: .
    container_name: app-web-simple
    image: cat_app/cat_app_docker
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/cat_app?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db