apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  selector:
    app: app-deployment
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8005
  type: LoadBalancer