spring:
  application:
    name: catapp
  jpa:
    show-sql: true
    hibernate:
      dialect: MySQL8Dialect
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:33060/cat_app
    # username: root
    # password: 123456
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}